# CPF Configuration File

framework:
  version: "1.0.0"
  name: "Cybersecurity Psychology Framework"
  
model:
  bayesian_network:
    inference_method: "variable_elimination"
    max_iterations: 1000
    convergence_threshold: 0.001
    
  calibration:
    milgram_compliance_high: 0.65
    milgram_compliance_low: 0.21
    kahneman_error_multiplier: 3.2
    bion_basic_assumption_prob: 0.73
    cialdini_social_proof: 0.87
    stress_activation_time: 0.25
    
data_generation:
  default_duration_days: 180
  default_org_size: 1000
  stress_event_probability: 0.15
  incident_base_rate: 0.01
  
  org_profiles:
    financial:
      hierarchy_levels: 7
      baseline_stress: 0.65
      compliance_culture: 0.8
      tech_maturity: 0.7
      
    healthcare:
      hierarchy_levels: 5
      baseline_stress: 0.75
      compliance_culture: 0.85
      tech_maturity: 0.5
      
    technology:
      hierarchy_levels: 3
      baseline_stress: 0.7
      compliance_culture: 0.4
      tech_maturity: 0.95
      
    government:
      hierarchy_levels: 8
      baseline_stress: 0.5
      compliance_culture: 0.9
      tech_maturity: 0.4
      
validation:
  bootstrap_iterations: 1000
  cross_validation_folds: 5
  significance_level: 0.05
  
  thresholds:
    green: 0.3
    yellow: 0.6
    critical_convergence: 0.7
    
soc_integration:
  update_interval_seconds: 300
  alert_threshold: 0.7
  min_aggregation_size: 10
  privacy_epsilon: 0.1
  
  siem_connectors:
    - splunk
    - elastic
    - qradar
    - sentinel
    
visualization:
  default_colormap: "RdYlGn_r"
  figure_dpi: 100
  save_format: "png"