qualys:
  username: your_qualys_username
  password: your_qualys_password
  api_url: https://qualysapi.qualys.com/api/2.0/fo/
  platform: "qualys_eu"

tenable:
  access_key: your_tenable_access_key
  secret_key: your_tenable_secret_key
  api_url: https://cloud.tenable.com/

rapid7:
  api_key: your_rapid7_api_key
  api_url: https://us.api.insight.rapid7.com/vm/v3/

# Optional dashboard configuration
dashboard:
  api_endpoint: https://dashboard.internal/api/cpf
  auth_token: your_dashboard_auth_token  # If required
